### ISSUE TITLE
Lighthouse runs at the same time as the other tests

### ISSUE THREAD

**Issue by ckhampus** [sitespeedio/plugin-lighthouse#1]
This is might be more of an observation and/or question, than an issue, so I apologize if this is the wrong place for it.

I have been playing around with the Lighthouse plugins since the release of 7.5.0 (🎉) and noticed that it seems to run at the same time as the regular Sitespeed tests. This causes the first run of several to be slower than the remaining runs and the Lighthouse scores seem to be also lower than they should be 🤔 Shouldn't the Lighthouse tests run after all the other tests?

Also as an aside: What's the recommended approach using the Lighthouse plugin when using Sitespeed with external throttling (`tsproxy`)? Should one use the `--lighthouse.throttlingMethod provided` option when running Sitespeed?

Thanks for the awesome work!

**Comment by soulgalore** [comment]
Hey @ckhampus it works perfectly to ask here. You are right, right now the test runs as same as Browsertime (it's hooked on when URLs are passed around). This is bad because it will interfere with the Browsertime runs, we should add that to the documentation so that is clear. One way to fix that in the future would be to make Lighthouse collect the URLs and then act on browsertime.finished message (or something like that). The message system needs some more documentation (you can see parts here: https://www.sitespeed.io/documentation/sitespeed.io/plugins/#important-messages but we need more).

My idea is that Lighthouse has good recommmendation (the rules or what it's called) and that's the main point of why you wanna run it. The timing metrics from Lighthouse isn't something I would use since it's guestimates and/or using the screenshots to calculate the visual metrics. Plus there are documentated limitations for slow sites (max limit of screenshots etc). Also since it (at least our implementation) is based on one run, the metrics will be unstable. However feel free to use it but we canot guarantee that you get stable metrics the way we do with Browsertime.

But it's a problem that they run at the same time, so I wouldn't turn in Lighthouse right now if you continously run sitespeed.io on a server, only use it locally when you test. Let me think a couple of days how we can fix this the best way.

Best
Peter

**Comment by soulgalore** [comment]
Another way to temporary fix it is to make two different runs and disable Browsertime for one of the runs. I've updated the docs for how to do that: https://www.sitespeed.io/documentation/sitespeed.io/lighthouse/

That will work for getting metrics in Graphite/InfluxDb but will be bad since you will have two different HTML outputs.

**Comment by ckhampus** [comment]
Ok, was unsure if there was something I missed, but I understand now. I will play around with it a bit more and see if we can get some usable results 👍 Thanks!

**Comment by soulgalore** [comment]
I think I can have fix ready tonight so don't spend so much time on it today :)

**Comment by soulgalore** [comment]
I've pushed 7.5.2 with the latest version of the plugin that now waits for each Browsertime test to finish before it starts. Let me know if it works fine for you.

**Comment by ckhampus** [comment]
I've just tested 7.5.2 and it seems to be working as expected now. Lighthouse is running after the other tests now 👍 Thanks for looking into this this so quickly!
