### ISSUE TITLE
Add support for --debug

### ISSUE THREAD

**Issue by gidztech** [sitespeedio/plugin-lighthouse#12]
The Lighthouse CLI provides a `logLevel` flag, which means it's possible to make the Lighthouse audit logs more verbose. For example:

```js
lighthouse(url, { 
    port: chrome.port, 
    logLevel: 'verbose'
}, config);
```

However, the `--debug` flag for SitespeedIO is not currently respected by the Lighthouse plugin. It would be good if the flag was passed through to Lighthouse, so it's possible to debug errors.

I'm a little confused by `--verbose` vs `--debug` but I think this is more of a debugging flag as you get a huge amount of raw data from Lighthouse.

**Comment by soulgalore** [comment]
Yeah, there's no real docs there. It works like this: --verbose or multiple -v change the log level. So for example if you want log on the lowest level in sitespeed.io you use -vvv. 

The --debug is logging the internal queue messages (yep the name of that isn't perfect) so that you can more easily follow what happens in the background how messages are passed around in the queue.


I've changed now so when the next release goes out you can use --verbose (as you do with sitespeed.io) to get the log.
