### ISSUE TITLE
Disable network throttling using Lighthouse

### ISSUE THREAD

**Issue by aravindhan87** [sitespeedio/plugin-lighthouse#23]
Team,

I am trying to run the lighthouse runs without network throttling and to run it on the desktop. Looks like both the commands are not working as expected. 

--lighthouse.extends lighthouse:default --lighthouse.settings.output html --lighthouse.settings.emulatedFormFactor desktop --lighthouse.settings.useThrottling false

Can you please help me if anything wrong with the command.

**Comment by soulgalore** [comment]
Hi @aravindhan87 not sure, I don't use Lighthouse. It seems they have different config in the cli and using it programmatically. Doesn't run in simulated mode by default? One way to check if it works or not is to add `--verbose` to your run, it will make Lighthouse log everything.
 
Best
Peter

**Comment by aravindhan87** [comment]
Thanks Peter for the response.

Lighthouse is currently running in simulated mode by default. But I am trying to override the options like running in Desktop mode and disabling the network throttling. 

To do that I have used the examples given in the README.md but still I couldn't override my options.

This is the exact command I am giving. 

docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.5.1-plus1 https://www.sitespeed.io/ --plugins.add analysisstorer --plugins.add /lighthouse --lightHouseConfig.extends lighthouse:default --lightHouseConfig.settings.output html -n=1

Thanks
Aravindhan

**Comment by venkatrayapudi** [comment]
I have the same problem. How can we solve this?

**Comment by omares** [comment]
Hey,

i was also curious on how to disable the network throttling and toyed around with various options.

After not being able to remove the throttling, i created an issue in the lighthouse repo GoogleChrome/lighthouse#8986 which includes my findings.

**Comment by soulgalore** [comment]
I had a go and using `throttlingMethod: 'provided' ` fix it for me. I'll make that default in the coming release since it will automatically use the throttled connection used by sitespeed.io and add docs on how to override it.

**Comment by omares** [comment]
@soulgalore please dont do so! This will also disable the CPU throttling. The correct options to disable network throttling are as follows.

`--lighthouse.extends lighthouse:default --lighthouse.settings.throttlingMethod devtools --lighthouse.settings.throttling.requestLatencyMs 0 --lighthouse.settings.throttling.downloadThroughputKbps 0 --lighthouse.settings.throttling.uploadThroughputKbps 0`

The values are based on the feedback from the issue i opened.

**Comment by soulgalore** [comment]
Hi @omares I was thinking this was more of a feature :) Yeah I checked your upstream issue, the way it is right now is quite broken with simulated running on a throttled connection? 

But I'm not big fan of the timing metrics that you get from Lighthouse since its based on one run only, no real throttling, speed index from devtools etc, I think there's an issue somewhere where I explained it some more. That's why we only send the other scores by default to Graphite/InfluxDB,

But since I'm no Lighthouse user, it could be I'm wrong :) So let me know what you think, so I can correct it before we roll out the new version.

FYI: The cpu throttling is implemented in Browsertime 5 and coming in next sitespeed.io, released the coming week. 

Best
Peter

**Comment by omares** [comment]
> Hi @omares I was thinking this was more of a feature :) Yeah I checked your upstream issue, the way it is right now is quite broken with simulated running on a throttled connection?

Do you mean running lighthouse with simulated inside a [throttled sitespeed.io environment](https://www.sitespeed.io/documentation/sitespeed.io/connectivity/)? If yes, i agree that it is broken because then one is running throttling inside throttling ;)

> But I'm not big fan of the timing metrics that you get from Lighthouse since its based on one run only, no real throttling, speed index from devtools etc

Yeah its a bummer that its only a single run, thats why we are sending more metrics from insights to graphite so we have historical data we can build upon. But the most  reliable/consistens metrics we have are from the webpagetest runs with lighthouse enabled.

> I think there's an issue somewhere where I explained it some more. That's why we only send the other scores by default to Graphite/InfluxDB,

Could you provide me with the link? The lighthouse scoring is one of the only sources of measurement you get when it comes to google, scoring and SEO. (as performance is now part of their algorithm.) Thus it has some kind of credibility, especially for non tech people.

> But since I'm no Lighthouse user, it could be I'm wrong :) So let me know what you think, so I can correct it before we roll out the new version.

My suggestion would be to wait and see what patrickhulce, from the upstream issue, has to say on the last finding. I would prefer to not use `provided` as long as the whole sitespeed container is not throttled on all ends.

> FYI: The cpu throttling is implemented in Browsertime 5 and coming in next sitespeed.io, released the coming week.

When i get the changelog correctly this will uses the build in chrome throttling? Meaning this will not throttle the whole environment/docker container?

**Comment by soulgalore** [comment]
It works like this now: If you run the container and use browsertime and throttling using Docker networks, Lighthouse run simulated on the throttled connection. If you use Throttle, then you are not using a throttle connection for Lighthouse, so it kind of depends. It's super either way I think, but if disable throttling by default and then make it easy to turn it maybe. If breaks for people we can just roll that back.

> But the most reliable/consistens metrics we have are from the webpagetest runs with lighthouse enabled.

Using simulated or using actual connection on a real phone or desktop using emulated mobile? Hehe it differs I think. By default Lighthouse doesn't use [(the broken) devtools network](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md), it uses simulated. Meaning they guess the metrics and the algoritm is made so the metrics are stable caused are based on the same calculation. I call it guesstimates :) Not saying it isn't good, but maybe not the same as when you measure with other tools.

I wrote a little about what I think is broken measuring with Lighthouse here: https://github.com/sitespeedio/sitespeed.io/pull/1756#issuecomment-339941435 but one thing has changed: First Meaningful paint/contentful paint etc seems to be much better now that it was when it was first released. I keep a close I on them for Wikipedia and they are better now (at least for us).

From my point of view I would use (or rather if I would use Lighthouse) I would use it for the scores for the non devs in the organisation and then use sitespeed.io/browsertime/webpagetest to collect real metrics that you as a developer can act on. But thats why I think, I respect other opinions :)

> When i get the changelog correctly this will uses the build in chrome throttling? 

Yes. Pat Meenan tweeted about it some time ago that he has seen that it works as good as using cgroup. on Linux. The bad thing is that it will only work for Chrome but the good thing it's only throttling Chrome, not the full container.

Best
Peter

**Comment by soulgalore** [comment]
So I reverted that change so it runs in simulated connection by default.

**Comment by therealpecus** [comment]
I am hitting the same issue, and have been following the thread, peeking at the code, and making tests. I am not sure this would work:
```
--lighthouse.settings.throttlingMethod=provided --lighthouse.settings.cpuSlowdownMultiplier 4
```
Is there any way to actually verify what settings are used? The report states that both connection and cpu speed are `provided`, but the `cpuSlowdownMultiplier` parameter is available in the JSON with the results as a configuration, so I am perplexed. Does `throttlingMethod` override the other settings *even when explicitely provided*?

**Comment by soulgalore** [comment]
The Lighthouse report has a "runtime setting" where you can see what was used for your test.
