### ISSUE TITLE
Lighthouse report

### ISSUE THREAD

**Issue by omares** [sitespeedio/plugin-lighthouse#5]
Hey,

what kind of options do i have to configure to store the generated lighthouse html report? I would like to verify the throttle settings the plugin applies, as i am not sure if lighthouse throttles itself inside my throttled docker container.

Thanks!

**Comment by soulgalore** [comment]
Hi @omares there's no options at the moment. When I implemented it there where no sane way of getting the HTML and incorporate it into our pug file, but maybe that has changed, I haven't looked for a while. But would be cool if there was a way to incorporate it?

So I would personally not use the Lighthouse performance metrics since it by default using simulated throttling and the alternative is their devtools throttling (see https://github.com/GoogleChrome/lighthouse/blob/08dbb45c886db7ed7853d55b530be4da66a6f7d8/docs/throttling.md#how-do-i-get-high-quality-packet-level-throttling).

Best
Peter

**Comment by SemyonLosmakov** [comment]
Hi, @soulgalore , 
According to documentation, looks like Lighthouse supports multiple outputs:
` interface SharedFlagsSettings {
      // The output types (json, html, ...)
      output?: OutputMode|OutputMode[];
// The locale setting
....
`

I tried to run sitespeed with:
`lighthouse": {
    "extends": "lighthouse:default",
    "settings": {
        "throttlingMethod": "provided",
        "maxWaitForLoad":"35000",
        "output":["json","html"]
    }
  }` in my config file, but I cannot find this html report from Lighthouse. 

Could you take a look on this issue again, please?

**Comment by soulgalore** [comment]
But its the same right, it will generate a full standalone HTML, I think incorporate it into our structure is the way forward as we do with all the other tools.

**Comment by SemyonLosmakov** [comment]
It would be great to have full Lighthouse report inside Sitespeed.io html-report, but is it possible now to get Lighthouse's html report from Sitespeed-plus1 test run?

**Comment by soulgalore** [comment]
Yeah maybe I haven't tried. If you have time please have look if you can have a look what's wrong.

**Comment by omares** [comment]
Hey @soulgalore, super sorry to not reply earlier!

I just found out that PR #18 totally achieves what i wanted and thus i am closing the issue.

Thanks a lot for the effort and passion you put into sitespeed. 💌
