### ISSUE TITLE
Add FirstContentfulPaint and FirstCPUIdle to save list in DB

### ISSUE THREAD

**Issue by MaximSergeichik** [sitespeedio/plugin-lighthouse#7]
Hi,

We would like to see FirstContentfulPaint and FirstCPUIdle metrics from lighthouse In Databases.
How it's better to do?
At the moment I see at least one solution is to add paths to this metrics into index.js file in DEFAULT_SUMMARY_METRICS variable. Will you merge such pull request? Or could you please suggest better solution for this optinon?

**Comment by soulgalore** [comment]
Hi @MaximSergeichik best case you could do this with just configuration, lets try that first. All the metrics that are collected with sitespeed.io and different plugins are JSON blobs where the keys are parent.children etc. All that is described here: https://www.sitespeed.io/documentation/sitespeed.io/metrics/

Its not perfect and I haven't used it in a while but I will try to guide you. First you need to find the correct metrics path to the metric you wanna include. You can do that by following https://www.sitespeed.io/documentation/sitespeed.io/metrics/#list-metrics and you need to run Lighthouse at the same time, so sitespeed.io pick up those metrics.
I did a test run and run the plugin like this:
`--plugins.add ../plugin-lighthouse/ https://www.sitespeed.io/ -n 1 --metrics.list`
and then in the root data folder I open the metrics.txt file (that is large since Lighthouse generates a lot of metrics).

Search for **lighthouse.pageSummary.** there you will have all the metrics that are collected for one page. When I looked I wonder if **lighthouse.pageSummary.audits.first-cpu-idle.rawValue** and **lighthouse.pageSummary.audits.first-contentful-paint.rawValue** is the right ones (I'm not familiar with the Lighthouse data structure).

The look at the docs on how you can send them: https://www.sitespeed.io/documentation/sitespeed.io/metrics/#add-a-metric

Hopefully this will work for you, please let me know!

Best
Peter

**Comment by MaximSergeichik** [comment]
Hi @soulgalore 

I used you suggestion about metrics.list and now I have necessary metrics in my graphite namespace. Thank you for quick reply!

Best regards,
Maksim

**Comment by soulgalore** [comment]
Great!
